name: delete
on:
  workflow_dispatch:
jobs:
  clean:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: Delete Website
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            unalias rm
            rm -rf pub/jzohdi/cmsc389T-web-template
