name: update
on:
  push:
    branches: [main]
#  workflow_dispatch: # uncomment this line and comment above to disable deploy on push
jobs:
  deploy:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Update Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            touch ~/.ssh/known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            mkdir -p pub/jzohdi/cmsc389T-web-template
            cd /pub/jzohdi/cmsc389T-web-template
            git init
            git remote add origin git@github.com:jzohdi/cmsc389T-web-template.git
            git pull
